### ISSUE TITLE
GraphNode: batch dispose mode

### ISSUE THREAD

**Issue by kzhsw** [donmccurdy/property-graph#83]
When using `dedup` or `prune` function in [glTF-Transform](https://github.com/donmccurdy/glTF-Transform), the functions could dispose a large amount of accessors, in a model with large amount of accessors, the `dispose` event listener in `GraphNode#addRef` consumes ~43% of the total CPU time.

<details><summary>screenshot</summary>
<p>

![the screenshot of chrome devtools profiler](https://user-images.githubusercontent.com/120431159/236135796-fd4b2bae-6749-40a5-b47d-2dc4eb55db2e.png)
![the screenshot of chrome devtools](https://user-images.githubusercontent.com/120431159/236136139-3d902588-0f51-49c3-bd97-daa78ca3acaf.png)

</p>
</details> 

### Proposal

Add batch dispose mode to GraphNode, in this mode, dispose events are buffered and processed later, so less array filter and push is called.

<details><summary>The patch to property-graph</summary>
<p>

```diff
--- /orig/property-graph.esm.js        2023-04-17 08:45:39.767000000 +0800
+++ /patched/property-graph.esm.js    2023-05-04 14:56:49.944723600 +0800
@@ -312,6 +312,8 @@
     this.graph = graph;
     this[$immutableKeys] = new Set();
     this[$attributes] = this._createAttributes();
+    this.$disposedRef = {};
+    this.$batchDispose = false;
   }
   /**
    * Returns default attributes for the graph node. Subclasses having any attributes (either
@@ -506,14 +508,9 @@
     const refs = this[$attributes][attribute];
     return refs.map(ref => ref.getChild());
   }
-  /** @hidden */
-
+  disposeRef(ref, attribute, refs) {
+    if (!this.$batchDispose) {

-  addRef(attribute, value, attributes) {
-    const ref = this.graph.createEdge(attribute, this, value, attributes);
-    const refs = this[$attributes][attribute];
-    refs.push(ref);
-    ref.addEventListener('dispose', () => {
       const retained = refs.filter(l => l !== ref);
       refs.length = 0;

@@ -523,6 +520,49 @@
         type: 'change',
         attribute
       });
+      return;
+    }
+    let disposed = this.$disposedRef[attribute];
+    if (!disposed) {
+      this.$disposedRef[attribute] = disposed = [];
+    }
+    disposed.push(ref);
+  }
+
+  startBatchDispose() {
+    this.$batchDispose = true;
+  }
+
+  commitBatchDispose() {
+    for (let attribute in this.$disposedRef) {
+      let disposed = this.$disposedRef[attribute];
+      if (!disposed.length) {
+        continue;
+      }
+      let set = new Set(disposed);
+      disposed.length = 0;
+      const refs = this[$attributes][attribute];
+      const retained = refs.filter(l => set.has(l));
+      refs.length = 0;
+
+      for (const retainedRef of retained) refs.push(retainedRef);
+
+      this.dispatchEvent({
+        type: 'change',
+        attribute
+      });
+    }
+    this.$batchDispose = false;
+  }
+  /** @hidden */
+
+
+  addRef(attribute, value, attributes) {
+    const ref = this.graph.createEdge(attribute, this, value, attributes);
+    const refs = this[$attributes][attribute];
+    refs.push(ref);
+    ref.addEventListener('dispose', () => {
+      this.disposeRef(ref, attribute, refs);
     });
     return this.dispatchEvent({
       type: 'change',


```

</p>
</details> 

<details><summary>The patch to @gltf-transform/functions</summary>
<p>

```diff
--- /orig/functions.modern.js	2023-05-04 14:42:15.841948800 +0800
+++ /patched/functions.modern.js	2023-05-04 15:03:40.144841900 +0800
@@ -1445,9 +1445,10 @@
       }
     });
   });
+  document.getRoot().startBatchDispose();
   Array.from(duplicateIndices.keys()).forEach(indices => indices.dispose());
   Array.from(duplicateAttributes.keys()).forEach(attribute => attribute.dispose()); // Dissolve duplicate animation sampler inputs and outputs.
-
+  document.getRoot().commitBatchDispose();
   for (const animation of document.getRoot().listAnimations()) {
     for (const sampler of animation.listSamplers()) {
       const input = sampler.getInput();
@@ -1463,8 +1464,10 @@
     }
   }
 
+  document.getRoot().startBatchDispose();
   Array.from(duplicateInputs.keys()).forEach(input => input.dispose());
   Array.from(duplicateOutputs.keys()).forEach(output => output.dispose());
+  document.getRoot().commitBatchDispose();
 }
 
 function dedupMeshes(document) {
@@ -1756,6 +1759,7 @@
     const disposed = {}; // Prune top-down, so that low-level properties like accessors can be removed if the
     // properties referencing them are removed.
     // Prune empty Meshes.
+    root.startBatchDispose();
 
     if (propertyTypes.has(PropertyType.MESH)) {
       for (const mesh of root.listMeshes()) {
@@ -1764,21 +1768,43 @@
         markDisposed(mesh);
       }
     }
+    root.commitBatchDispose();
 
     if (propertyTypes.has(PropertyType.NODE) && !options.keepLeaves) root.listScenes().forEach(nodeTreeShake);
+
+
+    root.startBatchDispose();
     if (propertyTypes.has(PropertyType.NODE)) root.listNodes().forEach(treeShake);
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
     if (propertyTypes.has(PropertyType.SKIN)) root.listSkins().forEach(treeShake);
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
     if (propertyTypes.has(PropertyType.MESH)) root.listMeshes().forEach(treeShake);
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
     if (propertyTypes.has(PropertyType.CAMERA)) root.listCameras().forEach(treeShake);
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
 
     if (propertyTypes.has(PropertyType.PRIMITIVE)) {
       indirectTreeShake(graph, PropertyType.PRIMITIVE);
     }
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
 
     if (propertyTypes.has(PropertyType.PRIMITIVE_TARGET)) {
       indirectTreeShake(graph, PropertyType.PRIMITIVE_TARGET);
     } // Prune unused vertex attributes.
 
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
 
     if (!options.keepAttributes && propertyTypes.has(PropertyType.ACCESSOR)) {
       for (const mesh of root.listMeshes()) {
@@ -1795,6 +1821,8 @@
     // (3) Remove samplers orphaned in the process.
 
 
+    root.commitBatchDispose();
+
     if (propertyTypes.has(PropertyType.ANIMATION)) {
       for (const anim of root.listAnimations()) {
         for (const channel of anim.listChannels()) {
@@ -1814,14 +1842,27 @@
       }
     }
 
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
     if (propertyTypes.has(PropertyType.MATERIAL)) root.listMaterials().forEach(treeShake);
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
     if (propertyTypes.has(PropertyType.TEXTURE)) root.listTextures().forEach(treeShake);
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
     if (propertyTypes.has(PropertyType.ACCESSOR)) root.listAccessors().forEach(treeShake);
+    root.commitBatchDispose();
+
+    root.startBatchDispose();
     if (propertyTypes.has(PropertyType.BUFFER)) root.listBuffers().forEach(treeShake); // TODO(bug): This process does not identify unused ExtensionProperty instances. That could
     // be a future enhancement, either tracking unlinked properties as if they were connected
     // to the Graph, or iterating over a property list provided by the Extension. Properties in
     // use by an Extension are correctly preserved, in the meantime.
 
+    root.commitBatchDispose();
     if (Object.keys(disposed).length) {
       const str = Object.keys(disposed).map(t => `${t} (${disposed[t]})`).join(', ');
       logger.info(`${NAME$3}: Removed types... ${str}`);

```

</p>
</details> 

<details><summary>screenshot after patch</summary>
<p>

![screenshot profiler](https://user-images.githubusercontent.com/120431159/236138637-b75dc6f8-909e-4fd5-94ec-ec7d4296458b.png)
![screenshot code](https://user-images.githubusercontent.com/120431159/236138820-abd99328-f83f-43a5-8a2b-edb9ed8171d7.png)
![screenshot code](https://user-images.githubusercontent.com/120431159/236138878-4de4f93b-1ddb-4d21-938b-892cf84817e0.png)

</p>
</details> 

Total blocking time reduced from ~26312ms to ~10332ms, GC time was also reduced after patch.

### Additional context

The model contains ~30000 accessors.
The model contains some business stuff which can not be shared, but any model with many duplicated or unused accessors or nodes could reproduce.
This is not a breaking change since everything would work like not patched without calls to `startBatchDispose` or `commitBatchDispose`.
Should note that in batch dispose mode, less duplicated `change` events are dispatched.

**Comment by donmccurdy** [comment]
A while ago I'd been looking into using `Set` to represent reference lists rather than `Array`. Never completed the PR, but I wonder if that would be a better way to handle this? I don't know if I'm keen to introduce a batch mode specifically for disposing things. This should make the hot code in the dispose callback much faster I think.

Related:

- https://github.com/donmccurdy/property-graph/pull/44
- https://github.com/donmccurdy/property-graph/issues/20
- https://github.com/donmccurdy/glTF-Transform/discussions/520

**Comment by kzhsw** [comment]
Possible alternatives:
1. Root#disposeRefs

```typescript
class Root {
  disposeRefs<K extends RefListKeys<Attributes>>(attribute: K, refs: (Attributes[K]) => boolean | Attributes[K][]) {
    this.startBatchDispose();
    // do the dispose here
    this.commitBatchDispose();
  }
}
```
2. delete and defragment

```typescript
class GraphNode {
  constructor(graph: Graph<GraphNode>) {
    this.dirtyMap = {};
  }

  disposeRef(ref, attribute, refs) {
    let index: number;
    let changed = false;
    while ((index = refs.indexOf(ref)) > -1) {
      refs[index] = null;
      changed - true;
    }
    if (changed) this.dirtyMap[attribute] = true;
  }
  listRefs(attribute) {
    const refs = this[$attributes][attribute];
    if (this.dirtyMap[attribute]) {

      const retained = refs.filter(l => l !== null);
      refs.length = 0;

      for (const retainedRef of retained) refs.push(retainedRef);

      this.dispatchEvent({
        type: 'change',
        attribute
      });
      this.dirtyMap[attribute] = false;
    }
    return refs.map(ref => ref.getChild());
  }
}
```

3. using data structures like binary tree or [rope](https://en.wikipedia.org/wiki/Rope_(data_structure))

**Comment by donmccurdy** [comment]
That we still need to rebuild the array of everything that wasn't disposed is unfortunate. Using Sets would really be ideal, to avoid:

```js
for (const retainedRef of retained) refs.push(retainedRef);
```

But this requires breaking API changes I'm not ready to make right now. In the meantime I think the simplest and safest optimization may be something like this:

- https://github.com/donmccurdy/property-graph/pull/84

**Comment by donmccurdy** [comment]
Relevant for benchmarking, the model linked below contains about 40,000 accessors. Disposing 50% of those could be a comparable test.

https://sketchfab.com/3d-models/plant-3-5ecd9744ff6f4aa09766d796eec161ee

**Comment by kzhsw** [comment]
A much simplier idea for benchmarking
```javascript
const doc = new Document();
const count = 10000;
const listRefs = 100;
for (let i = 0; i < count; i++)
  doc.createAccessor();
const accessors = doc.getRoot().listAccessors();
for (let i = 0; i < count; i+=2)
   accessors[i].dispose();
for (let i = 0; i < listRefs ; i++)
   doc.getRoot().listAccessors();
```

**Comment by donmccurdy** [comment]
While I fully agree it would be much faster, I don't think I can justify adding a batch API for disposal. We are dispatching events, user code may execute in those callbacks, and there's potential for this to go sideways in complex ways. 

Storing refs in a Set is both faster and safer. I'd much rather do that, in a future major version. I the meantime I would prefer to take a safer option (#84) for a smaller speed improvement.

That said — it might help to understand better the kind of processing you're doing with glTF Transform, your performance goals, and what is working well vs. not well in general? Please feel free to start a thread if that would be helpful.

**Comment by kzhsw** [comment]
> We are dispatching events, user code may execute in those callbacks, and there's potential for this to go sideways in complex ways.

Is the `change` event required to be fired every time disposing GraphNodes? The `change` event contains only the attribute, not the disposing node.
Maybe off-topic, but since `dispatchEvent` takes considerable cpu time in results above, maybe users could have options to choose which events they use, to have the trade-off between feature and performance, where all events enabled by default for backward-compatibility.

**Comment by donmccurdy** [comment]
We can't turn off `dispatchEvent` entirely — a few internals rely on the `create` and `dispose` events — but I think an option to disable `change` events would be possible.

**Comment by donmccurdy** [comment]
@kzhsw as FYI: https://github.com/donmccurdy/glTF-Transform/issues/1527#issuecomment-2438148280
